# launch command: vagrant up --provider=aws
require 'vagrant-aws'
Vagrant.configure("2") do |config|
    config.vm.box = "dummy"

    config.vm.provider :aws do |aws, override|
        override.vm.synced_folder ".", "/vagrant", disabled: true
        aws.aws_profile = "wjav.admin"
        aws.region = "eu-west-1"
        aws.instance_type = "t2.small"
        aws.security_groups = ['sg-1cae1e67']
        aws.associate_public_ip = "true"
        aws.subnet_id = "subnet-0241694b"
        aws.keypair_name = "inttest"

        aws.terminate_on_shutdown = "true"

        aws.ami = "ami-0a166fb5b1a5d9532" # regional amzn2-ami-hvm-2.0.20181114-x86_64-ebs

        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "inttest.pem"
        
    end
        config.vm.provision "ansible" do |ansible|
            ansible.playbook = "nginx.yml"
            ansible.extra_vars = {
            version: "2.2.0",
            service: "tomcat",
            domain: "tf-test",
            service_port: "8080"
            }
        end
    
end
